// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK6yfTtXQLqq1QTHXGRet-cdh437-EjgE',
    appId: '1:881974623024:web:5ee5a2a9634c61fdab66f5',
    messagingSenderId: '881974623024',
    projectId: 'student-clearance-system-6c2e2',
    authDomain: 'student-clearance-system-6c2e2.firebaseapp.com',
    storageBucket: 'student-clearance-system-6c2e2.appspot.com',
    measurementId: 'G-0DC8MRFMC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CH5H2e8DhhNrnplmZb_YFrFNl7wc2I8',
    appId: '1:881974623024:android:5bf862961c0b8851ab66f5',
    messagingSenderId: '881974623024',
    projectId: 'student-clearance-system-6c2e2',
    storageBucket: 'student-clearance-system-6c2e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATlxAsEqPgDsjRtvlk1GHBgiaV0iWz-0I',
    appId: '1:881974623024:ios:75bc0acd4866729cab66f5',
    messagingSenderId: '881974623024',
    projectId: 'student-clearance-system-6c2e2',
    storageBucket: 'student-clearance-system-6c2e2.appspot.com',
    iosClientId: '881974623024-gted9a5os554btle2dogu4jpdoka20pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentClearanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATlxAsEqPgDsjRtvlk1GHBgiaV0iWz-0I',
    appId: '1:881974623024:ios:5a95e47aaaf09221ab66f5',
    messagingSenderId: '881974623024',
    projectId: 'student-clearance-system-6c2e2',
    storageBucket: 'student-clearance-system-6c2e2.appspot.com',
    iosClientId: '881974623024-h82ab29uk35609csnruuncumvklq3h2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentClearanceApp.RunnerTests',
  );
}
